(function(global){
  'use strict';
  const median=values=>{const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2;};
  const merchant=value=>String(value||'').toUpperCase().replace(/\b(CARD|PAYMENT|CONTACTLESS|ONLINE|DIRECT DEBIT|DD|REF|REFERENCE)\b/g,' ').replace(/[^A-Z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
  const day=value=>Math.floor(Date.parse(`${value}T00:00:00Z`)/86400000);
  function grouped(transactions,predicate){const map=new Map();(transactions||[]).filter(predicate).forEach(transaction=>{const key=merchant(transaction.description);if(!key)return;const rows=map.get(key)||[];rows.push(transaction);map.set(key,rows);});return map;}
  function spendingAlerts(database,today){const alerts=[],todayDay=day(today);grouped(database.transactions,t=>t.amount<0&&!t.transferId&&!t.excluded&&t.status!=='pending').forEach((rows,key)=>{rows.sort((a,b)=>a.date.localeCompare(b.date));if(rows.length<4)return;const latest=rows[rows.length-1],baseline=rows.slice(0,-1).slice(-8).map(t=>Math.abs(Number(t.amount))),typical=median(baseline),actual=Math.abs(Number(latest.amount));if(todayDay-day(latest.date)<=60&&actual>=typical*1.75&&actual-typical>=10)alerts.push({id:`spend:${key}:${latest.id}`,type:'unusual-spending',severity:'review',title:`Unusual ${key.toLowerCase()} spending`,detail:`${money(actual)} versus a recent median of ${money(typical)} across ${baseline.length} earlier payments.`,transactionId:latest.id});});return alerts;}
  function subscriptionAlerts(database){const alerts=[];grouped(database.transactions,t=>t.amount<0&&!t.transferId&&!t.excluded&&/subscription/i.test(String(t.category||''))).forEach((rows,key)=>{rows.sort((a,b)=>a.date.localeCompare(b.date));if(rows.length<3)return;const latest=rows[rows.length-1],baseline=rows.slice(0,-1).slice(-6).map(t=>Math.abs(Number(t.amount))),typical=median(baseline),actual=Math.abs(Number(latest.amount));if(actual>=typical*1.1&&actual-typical>=1)alerts.push({id:`subscription:${key}:${latest.id}`,type:'subscription-increase',severity:'review',title:`${key.toLowerCase()} may have increased`,detail:`Latest ${money(actual)} versus a previous median of ${money(typical)}.`,transactionId:latest.id});});return alerts;}
  function missingIncomeAlerts(database,today){return (database.recurringItems||[]).filter(item=>item.status==='active'&&item.kind==='income'&&item.nextDate<today&&day(today)-day(item.nextDate)>3).map(item=>({id:`income:${item.id}:${item.nextDate}`,type:'missing-income',severity:'attention',title:`Expected income is late: ${item.name}`,detail:`Expected ${item.nextDate} for approximately ${money(item.amount)}; no occurrence has been confirmed.`,recurringItemId:item.id}));}
  function cardBillAlerts(database){const rows=(database.transactions||[]).filter(t=>t.amount<0&&!t.transferId&&!t.excluded&&/(CREDIT CARD|CARD PAYMENT|AMEX)/i.test(String(t.description||''))).sort((a,b)=>a.date.localeCompare(b.date));if(rows.length<4)return[];const latest=rows[rows.length-1],baseline=rows.slice(0,-1).slice(-6).map(t=>Math.abs(Number(t.amount))),typical=median(baseline),actual=Math.abs(Number(latest.amount));return actual>=typical*1.3&&actual-typical>=25?[{id:`card-bill:${latest.id}`,type:'card-bill-change',severity:'review',title:'Card bill differs from recent payments',detail:`Latest ${money(actual)} versus a recent median of ${money(typical)}.`,transactionId:latest.id}]:[];}
  function money(value){return `£${Number(value||0).toFixed(2)}`;}
  function analyse(database,options){const today=options&&options.today||new Date().toISOString().slice(0,10),dismissed=new Set((database.dismissedAlerts||[]).map(item=>typeof item==='string'?item:item.id));const alerts=[...missingIncomeAlerts(database,today),...subscriptionAlerts(database),...cardBillAlerts(database),...spendingAlerts(database,today)];const unique=[...new Map(alerts.map(alert=>[alert.id,alert])).values()];return {alerts:unique.filter(alert=>!dismissed.has(alert.id)),dismissed:unique.filter(alert=>dismissed.has(alert.id)),total:unique.length};}
  global.PocketLedgerAnomalies={median,merchant,spendingAlerts,subscriptionAlerts,missingIncomeAlerts,cardBillAlerts,analyse};
})(window);
